project:
  type: website
  output-dir: docs

website:
  title: "Fiches Ripp-Viti"
  page-navigation: true
  reader-mode: false
  navbar:
    background: secondary
    style: "docked"
    search: true
    left: 
      - href: index.qmd
        text: Introduction
      - text: La démarche
        href: methodo.qmd
      - text: "Fiches Leviers"
        menu:
          - L6_choixPulve.qmd
          - L1_optiPulve.qmd
          - L5_pulveConfinee.qmd 
          - L3_buses.qmd
          - L9_oad.qmd
          - L8_enh.qmd
          - L2_haies.qmd
          - L7_fosses.qmd
          - L4_varietes.qmd
      - text: "Fiches Exploitations"
        menu:
          - EA11.qmd
          - EA12.qmd
          - EA2A.qmd
          - EA2B.qmd
      - about.qmd
      - biblio.qmd
  page-footer:
    right: "Projet RIPPviti, 2024"
    left: "&copy; CC BY-NC-ND"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

lang: fr


