project:
  type: website
  output-dir: docs

website:
  title: "Fiches RIPP"
  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    contents: 
      - href: index.qmd
        text: Home
      - section: "Les leviers pour réduire les impacts environnementaux"
        contents:
          - L6_choixPulve.qmd
          - L1_optiPulve.qmd
          - L5_pulveConfinee.qmd 
          - L3_buses.qmd
          - L9_oad.qmd
          - L8_enh.qmd
          - L2_haies.qmd
          - L7_fosses.qmd
          - L4_varietes.qmd
      - section: "La stratégie exploitation"
        contents:
          - E1_AE11.qmd
      - about.qmd
      - biblio.qmd
  page-footer:
    right: "Projet RIPPviti, 2023"
    left: "&copy; CC BY-NC-ND"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

lang: fr


